spring:
  data:
    mongodb:
      database: ees-ms-users
      port: 27017
      host: localhost
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: localhost
#Keycloack
keycloak:
  realm: ees-ms-authentification
  auth-server-url: http://localhost:8080
  resource: ees-ms-keycloak
  credentials:
    secret: trKdGRGFZIJ5RF6jjuJQGZMGLQI6dzku
  use-resource-role-mappings: false
  bearer-only: true
  ssl-required: none
#Cloudinary Stockage Cloud
cloudinary:
  cloud-name: dq5xn9izs
  api-key: 135195339797177
  secret-key: H6fAcSZs1RQgPPQDqgsAeJ8H6dk
application:
  url: http://localhost:4200