apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: ees-ms-users-app
  labels:
    app: ees-ms-users-app
spec:
  selector:
    matchLabels:
      app: ees-ms-users-app
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: ees-ms-users-app
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017 # The port that the container is running on in the cluster
        env:
          - name: MONGO_URL
            value: "mongodb+srv://ees-intranet-web:ees-intranet-web@ees-intranet-web.mp0oobs.mongodb.net/?retryWrites=true&w=majority&appName=ees-intranet-web"
      - name: keycloak
        image: quay.io/keycloak/keycloak:latest
        args:
          - start
        ports:
        - containerPort: 8080 # The port that the container is running on in the cluster
        env:
          - name: KC_PROXY
            value: "edge"
          - name: KC_HOSTNAME
            value: "https://keycloak-enexse-u12566.vm.elestio.app/"
      - name: ees-ms-users-app
        image: enexse/ees-ms-users:latest # Image that will be used to containers in the cluster
        args: ["--spring.profiles.active=prod"]
        imagePullPolicy: Always
        ports:
        - containerPort: 9190 # The port that the container is running on in the cluster
        env:
          - name: EUREKA_SERVER_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: eureka-cm
                key: eureka_service_address
          - name: KEYCLOAK_REALM
            valueFrom:
              configMapKeyRef:
                name: eureka-cm
                key: keycloak_realm
          - name: KEYCLOAK_AUTH_SERVER_URL
            valueFrom:
              configMapKeyRef:
                name: eureka-cm
                key: keycloak_auth_server_url
          - name: KEYCLOAK_RESOURCE
            valueFrom:
              configMapKeyRef:
                name: eureka-cm
                key: keycloak_resource
          - name: KEYCLOAK_CREDENTIALS_SECRET
            valueFrom:
              configMapKeyRef:
                name: eureka-cm
                key: keycloack_credentials_secret

---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata:
  name: ees-ms-users-svc # Metadata of the resource kind we are creating
spec:
  selector:
    app: ees-ms-users-app
  ports:
    - port: 80 # The port that the service is running on in the cluster
      protocol: TCP
      targetPort: 9190 # The port exposed by the service
  type: ClusterIP # type of the service.
